from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version


def _read_version() -> str:
    try:
        return version("yanka")
    except PackageNotFoundError:
        try:
            from yanka._version import __version__ as v  # generated by hatch-vcs at build time

            return v
        except ModuleNotFoundError:
            return "0.0.0+unknown"


__version__ = _read_version()
